[package]
name = "hello_ggez"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ggez = "0.8.0-rc0"
rand = "0.8.5"
rapier2d = { version = "0.14", features = [ "simd-stable", "parallel" ] }
